name: MyFirstAction

on:
  pull_request:
    branches: 
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar repositorio
      uses: actions/checkout@v2

    - name: Paso 2
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'

    - name: Install Composer dependencies
      run: composer install

    - name: Run PHP_CodeSniffer
      run: vendor/bin/phpcs --standard=PSR2 application/